import { ColumnaInterface } from "../../../models/columna.interface";

export const DashboardTablaConfig: ColumnaInterface[] = [
    {
        nombre: 'control.control',
        campo: 'controlDescripcion',
        tamanyo: '15%',
        campoOrden: 'controlDescripcion',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'app.fechaHora',
        campo: 'fechaHora',
        tamanyo: '10%',
        campoOrden: 'fechaHora',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'data',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'app.tipoControl',
        campo: 'tipoControl',
        tamanyo: '15%',
        campoOrden: 'tipoControl',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'control.grupo',
        campo: 'grupo',
        tamanyo: '15%',
        campoOrden: 'grupo',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'app.indicador',
        campo: 'indicador',
        tamanyo: '15%',
        campoOrden: 'indicador',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'app.unidad',
        campo: 'unidad',
        tamanyo: '10%',
        campoOrden: 'unidad',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'app.valor',
        campo: 'valor',
        tamanyo: '10%',
        campoOrden: 'valor',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    },
    {
        nombre: 'control.nivelAlerta',
        campo: 'alerta',
        tamanyo: '10%',
        campoOrden: 'alerta',
        mostrarOrdenacion: true,
        ordenOrdenacion: null,
        filtroActivo: false,
        valorFiltro: '',
        tipoFiltro: 'text',
        ocultarBuscador: true,
        visibleExportacion: true,
        ordenDireccion: ['ascend', 'descend', null]
    }
]